export const FETCH_COMPANY_BANKACCOUNTS_SUCCESS =
    "FETCH_COMPANY_BANKACCOUNTS_SUCCESS";

export const FETCH_COMPANY_BANKACCOUNT_DETAILS_SUCCESS =
    "FETCH_COMPANY_BANKACCOUNT_DETAILS_SUCCESS";

export const CREATE_COMPANY_BANKACCOUNT_SUCCESS =
    "CREATE_COMPANY_BANKACCOUNT_SUCCESS";

export const UPDATE_COMPANY_BANKACCOUNT_SUCCESS =
    "UPDATE_COMPANY_BANKACCOUNT_SUCCESS";

export const DELETE_COMPANY_BANKACCOUNT_SUCCESS =
    "DELETE_COMPANY_BANKACCOUNT_SUCCESS";
