export const FETCH_COMPANIES_SUCCESS = "FETCH_COMPANIES_SUCCESS";

export const FETCH_COMPANY_DETAILS_SUCCESS = "FETCH_COMPANY_DETAILS_SUCCESS";

export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";

export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";

export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
