export const FETCH_COMPANY_BANK_BALANCE_SUCCESS =
    "FETCH_COMPANY_BANK_BALANCE_SUCCESS";

export const FETCH_COMPANY_BANK_BALANCE_DETAILS_SUCCESS =
    "FETCH_COMPANY_BANK_BALANCE_DETAILS_SUCCESS";

export const CREATE_COMPANY_BANK_BALANCE_SUCCESS =
    "CREATE_COMPANY_BANK_BALANCE_SUCCESS";

export const UPDATE_COMPANY_BANK_BALANCE_SUCCESS =
    "UPDATE_COMPANY_BANK_BALANCE_SUCCESS";

export const DELETE_COMPANY_BANK_BALANCE_SUCCESS =
    "DELETE_COMPANY_BANK_BALANCE_SUCCESS";
